### PR TITLE
Check if file index exists

### PR DESCRIPTION
**Pull request by aromka**
Fix for the error

Error in exception handler: Undefined index: file in /.../vendor/stackify/logger/src/Stackify/Log/Entities/ErrorWrapper.php:126

### CODE REVIEW

**Comment by aromka** [comment]
Perhaps this should be || instead of &&, if trace item should be included without file key?

**Comment by iWader** [comment]
+1 Traces without file and lines can still be useful when part of the full stack trace.

**Comment by eric-martin** [comment]
We will take a look. Thanks.

**Comment by eric-martin** [comment]
Thanks for the PR. We've merged your change in and are planning on making an additional enhancement before releasing a new version. I'll send an addition update on this thread when that is complete.

**Comment by eric-martin** [comment]
Version 1.0.4 is now available

**Pull request merged**
